### ISSUE TITLE
[LANG] French

### ISSUE THREAD

**Issue by Maddude174** [ShermansWorld/CharacterCards#12]
I've never done a translation before, so let me know if i missed anything.

```
# ========================================
#     CharacterCards par ShermansWorld   
# ========================================

# Signaler les bugs à https://github.comShermansWorldCharacterCards

config-version 8

# ====================================
#         PARAMÈTRES DE LANGUE        
# ====================================

# Intéressé à traduire CharacterCards dans une autre langue?
# Passer un message à https://github.comShermansWorldCharacterCardsissues, inclure [LANG] dans le titre!
# Vous pouvez également créer un nouveau fichier de langue localement et cela fonctionnera très probablement. Assurez-vous de respecter l’espacement et le format général!

lang enUS
# Les langues possibles enUS por l'anglais (États-Unis), ro pour le Roumain, ptBR pour le Portugais Brésilien, fr pour le Français
# Changer de langue nécessite un redémarrage du serveur!

# ======================================
#  PARAMÈTRES DE LA CARTE DE PERSONNAGE      
# ======================================

# Paramètres de ce que les joueurs peuvent saisir dans leurs cartes de personnage.
# Les cartes de personnage servent à améliorer l'expérience RPG et sont purement esthétiques.

MinAge 14
# L'âge le plus bas qu'un joueur peut définir.

MaxAge 120
# L'âge le plus élevé qu'un joueur peut définir.

DescCharLimit 512
# Définit la longueur maximale de la description d'un joueur. La valeur par défaut est 512 ou 2 messages de discussion complets.

CustomFields
  1
    label '&3Balance'
    placeholder '&b%vault_eco_balance_formatted%'
# Vous pouvez désormais définir autant de champs personnalisés que vous souhaitez ajouter aux cartes de personnage. Numérotez-les en commençant par 1.
# Pour effacer tous les champs personnalisés, remplacez cette section par CustomFields []
# Ces champs personnalisés dépendent de PlaceholderAPI (PAPI). Vous devez l'avoir installé pour que ces espaces réservés fonctionnent!
# Pour que l'espace réservé ci-dessus fonctionne, exécutez /papi ecloud download vault et /papi reload

# ====================================
#       PARAMÈTRES D'INTERACTION         
# ====================================

ShiftRightClick true
# Affiche la carte de personnage d'un joueur lorsqu'un joueur fait un clic droit dessus.

RightClickPaper true
# Affiche la carte de personnage d'un joueur lorsqu'un joueur clique dessus avec le bouton droit avec du papier à la main.

# =====================================
#          CROCHETS DE PLUGIN               
# =====================================

IntegratePAPI false
# Si votre serveur exécute PlaceholderAPI (PAPI), alors la fonctionnalité de champs personnalisés sera activée et ajoutée à la carte du joueur.

IntegrateTowny true
# Si votre serveur exécute Towny, la TownNation d'un joueur est ajoutée à sa carte de personnage.

IntegrateMythicalRaces true
# Si votre serveur exécute Mythical Races, puis la race d'un joueur est ajoutée à sa carte de personnage.

IntegrateKonquest true
# Si votre serveur exécute Konquest, le Royaume d'un joueur est ajouté à sa carte de personnage.

IntegrateMagic true
# Si votre serveur exécute le plugin Magic, le chemin de progression d'un joueur (débutant, étudiant, apprenti, maître, etc.) est ajouté à sa carte de personnage.
```

```
NoPermission: '&cVous n'avez pas la permission de faire cela'
NoColors: '&cVous ne pouvez pas utiliser de couleurs!'
EmptyField: 'Vide '
CharacterCardsCommands:
  Reload: '&3Recharge la config.yml'
  ReloadSuccess: '&econfig.yml rechargé'
CharacterCommands:
  NameHelp: '&7<&bPrénom&7> &7{&bDernier&7} &7{&bTitre&7} &8- &3Définissez le nom de votre personnage.'
  GenderHelp: '&7<&bMâle&7/&bFemelle/&bAutre&7> &8- &3Définir le sexe de votre personnage.'
  AgeHelp: '&3Définir l'âge de vos personnage.'
  DescHelp: '&7<&bDescription&7> &8- &3Définissez la description de vos personnage.'
  ViewHelp: '&7{&bJoueur&7} &8- &3Visualisez votre carte ou celle d'un autre joueur!'
  NameError1: '&cTrop d'arguments! &eUsage&7: &7/&cChar Name &7<&cPrénom&7> &7{&cDernier&7} &7{&cTitre&7}'
  NameError2: '&cVous devez entrer un nom!'
  NameSuccess: '&3Nom défini comme'
  GenderError1: '&cVous devez définir un sexe! &7(&eMâle&7/&eFemelle/&eAutre&7)'
  GenderError2: '&cTrop d'arguments! &eUsage&7: &7/&cChar Gender &7(&cMâle &7ou &cFemelle &7ou &cAutre)'
  GenderError3: '&cVous dois être: Mâle&7/&cFemelle&7/&cAutre'
  GenderSuccess1: '&3Sexe défini comme: &eMâle'
  GenderSuccess2: '&3Sexe défini comme: &eFemelle'
  GenderSuccess3: '&3Sexe défini comme: &eAutre'
  AgeError1: '&cVous devez définir un âge! Usage&7: &7/&cChar Age [âge]'
  AgeError2: '&cTrop d'arguments! &eUsage: &7/&cChar Age [âge]'
  AgeError3: '&7L'âge doit être'
  AgeSuccess: '&3Âge fixé comme'
  DescError1: '&cVous devez définir une description!'
  DescError2: '&cDescription est trop grande!'
  DescSuccess: '&3Description définie comme'
  DescCleared: '&aDescription effacée'
  ViewError1: '&cTrop d'arguments! &eUsage&7: &7/&cChar View &8<&cJoueur&8>'
  ViewError2: '&cCette carte n'existe pas! A-t-il été supprimé récemment?'
  ViewError3: '&7n'est pas en ligne/n'a jamais adhéré auparavant&3.'
  Invalid: '&cCommande non valide'
  DeleteSuccess: '@PLAYER''s &afichier de configuration supprimé!'
  DeleteError1: '@PLAYER''s &cfichier de configuration n'existe pas!'
  DeleteError2: ' &cn'est pas en ligne!'
  DeleteError3: '&cVous devez entrer le &enom d'un &ajoueur'
Cards:
  Name: Nom
  Gender: Sexe
  Age: Âge
  Desc: '@PLAYER''s Desc'
  Card: '@PLAYER''s Carte'
  Male: 'Mâle '
  Female: 'Femelle '
  Other: 'Autre '
```
